name: 'mirror-and-push'
on:
  push:
    branches:
        - __mirror
  schedule:
    # Run everyday at 3 AM UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions: 
  contents: write
  actions: write
  statuses: write 

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Fetch upstream
        run: |
          git remote add upstream "https://github.com/jellyfin/jellyfin-vue.git"
          git fetch upstream
          git fetch origin

      - name: Debug information
        run: |
          echo "Current branch:"
          git branch --show-current
          echo "All branches:"
          git branch -a
          echo "Remote branches:"
          git branch -r

      - name: Force update master branch
        run: |
          git checkout -b master || git checkout master
          git reset --hard upstream/master
          git status
          git branch
          git push origin master --force -v
