name: 'mirror'
on:
  push:
    branches:
        - __mirror
  schedule:
    # Run everyday at 3 AM UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: mirror
        run: |
          git remote add --mirror=fetch mirror "https://github.com/jellyfin/jellyfin-vue.git" || exit 1
          git fetch mirror +refs/heads/master:refs/remotes/origin/master || exit 1
          git push --force --mirror --prune origin || exit 1
          sleep 3
          curl -X POST -d '' "${{ secrets.DEPLOY_HOOK }}"
