name: 'mirror-and-push'
on:
  push:
    branches:
        - __mirror
  schedule:
    # Run everyday at 3 AM UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  mirror-and-push:
    runs-on: ubuntu-latest
    name: mirror-and-push
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add remote and fetch
        run: |
          git remote add upstream "https://github.com/jellyfin/jellyfin-vue.git"
          git fetch upstream

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Update local master
        run: |
          git checkout master
          git merge upstream/master

      - name: Push to origin
        run: |
          git push origin master
