name: 'mirror'
on:
  push:
    branches:
        - __mirror
  schedule:
    # Run everyday at 3 AM UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: Allow git safe directory
        run: git config --global --add safe.directory /github/workspace
      - name: mirror
        id: mirror
        uses: bridgelightcloud/github-mirror-action@v2
        with:
          origin: 'https://github.com/jellyfin/jellyfin-vue.git'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
