name: 'mirror-and-push'
on:
  push:
    branches:
        - __mirror
  schedule:
    # Run everyday at 3 AM UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions: 
  contents: write
jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Fetch upstream
        run: |
          git remote add upstream "https://github.com/jellyfin/jellyfin-vue.git"
          git fetch upstream

      - name: Force update default branch
        run: |
          DEFAULT_BRANCH=$(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)
          git reset --hard upstream/$DEFAULT_BRANCH
          git push origin $DEFAULT_BRANCH --force
